spring:
  datasource:
    url: jdbc:postgresql://172.17.205.29:5432/compounds_cmm_db
    username: alejandra
    password: alejandra*
    driver-class-name: org.postgresql.Driver
    initialization-mode: always  # Ensure the datasource is always initialized

  web:
    cors:
      allowed-origins: "http://localhost:3000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:mykeystore.jks
    key-store-password: alejandra
    key-store-type: JKS
    key-alias: cmm-backend